### ISSUE TITLE
Progress bar doesn't working...

### ISSUE THREAD

**Issue by themisir** [alikinvv/minimal-player#1]
![zur](https://user-images.githubusercontent.com/29130291/39676015-21bfbd98-5174-11e8-8e9e-ffde812c42c4.png)

**Comment by alikinvv** [comment]
Thanks, the problem is fixed.

Replace all lines in the file main.js:
`playhead.style.width = percentage * 4 + 'px';`

to:
` playhead.style.width = percentage + '%';`
